// authedUser
export const SET_AUTHED_USER = "SET_AUTHED_USER";

// users
export const RECEIVE_USERS = "RECEIVE_USERS";
export const UPDATE_USERS_OPTIMISTICALLY = "UPDATE_USERS_OPTIMISTICALLY";
export const REVERT_USERS_OPTIMISTICALLY = "REVERT_USERS_OPTIMISTICALLY";

// questions
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const REVERT_QUESTION = "REVERT_QUESTION";
